CREATE TABLE category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50) NOT NULL,
    depth       INT         NOT NULL,
    root_code   VARCHAR(30) NOT NULL,
    parent_code VARCHAR(30),
    code        VARCHAR(30) NOT NULL
);

ALTER TABLE category
    ADD CONSTRAINT uq_category_code UNIQUE (code);

CREATE INDEX idx_category_root_code_depth ON category (root_code, depth);

CREATE INDEX idx_category_parent_code ON category (parent_code);

