CREATE TABLE category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50) NOT NULL,
    depth       INT         NOT NULL,
    parent_code VARCHAR(30),
    code       VARCHAR(30) NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP NULL
);

ALTER TABLE category
    ADD CONSTRAINT uq_category_code UNIQUE (code);
